// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xqafdrojfsrrnjyngenl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhxYWZkcm9qZnNycm5qeW5nZW5sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwMjUwMzIsImV4cCI6MjA3MDYwMTAzMn0.FofMXNdtaz1-ssFHo0aAwZiILVZcYmDtr2cE-3WSio8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});